# This is only for bloomberg, we can make Jenkins run the unit tests inside of a container and remove this later
version: '2.4'
services:
  salt-proper-tests:
    image: "artprod.dev.bloomberg.com/bb-inf/salt-minion:2018.3.3"
    volumes:
      - .:/srv/sysca-salt
      - ./tests/bbcpu/:/bb/bin/
